[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "SoftwareEngineeringAssessment"
version = "0.0.1"
license = { text = "MIT" } 
authors = [
    { name = "Arjun Ryatt" },
    { name = "Rebecca Sizer" },
    { name = "Rachel Wellman" }
]
description = "A web-based application tool for annotating germline variant data"
readme = "README.md"
requires-python = ">=3.13"
keywords = ["sea_app", "VariantValidator", "Clinvar", "Genomics", "Annotation", "Database"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License"
]

dependencies = [
    "requests",
    "pandas>=2.0",
    "biopython>=1.80",
    "flask>=2.3",
    "openpyxl>=3.1.2"
]

[project.optional-dependencies]
test = ["pytest==7.4.3"]

[project.urls]
Homepage = "https://github.com/RebeccaSizer/Software_Engineering_Assessment_2025_AR_RW_RS"
Repository = "https://github.com/RebeccaSizer/Software_Engineering_Assessment_2025_AR_RW_RS"
Issues = "https://github.com/RebeccaSizer/Software_Engineering_Assessment_2025_AR_RW_RS/issues"
Documentation = ""

[tool.setuptools.packages.find]
where = ["."]