# This is a basic workflow to help you get started with Actions

name: Pytest + Codecov

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "tests_RS" ]
  pull_request:
    branches: [ "tests_RS" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # This sets up Python.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # This ensures that the pytest and pytest-cov dependencies have been installed.
      - name: Install dependencies
        run: pip install pytest pytest-cov

      # 'Run tests' is where the actual pytest commands are, in the workflow.
      # Note that last two commands have been commented-out. This is because the command before them includes them in its pytest. 
      - name: Run tests
        run: |  
          pytest --cov --cov-branch --cov-report=xml
          pytest --cov --junitxml=junit.xml -o junit_family=legacy
          pytest -q --cov=.
          pytest -q --cov=tools
          pytest -q --cov=tests
      # This uploads the pytest coverage results to Codecov.
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # This uploads the pytests to Codecov, including which lines in the code were missed. 
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
